// Bug-finding checks only. The page scripts are classic scripts that share globals across files,
// so undefined-name checks are left out and top-level declarations may be used elsewhere.
const bugs = {
  "constructor-super": "error",
  "for-direction": "error",
  "getter-return": "error",
  "no-async-promise-executor": "error",
  "no-compare-neg-zero": "error",
  "no-cond-assign": "error",
  "no-const-assign": "error",
  "no-constant-binary-expression": "error",
  "no-constant-condition": ["error", { checkLoops: false }],
  "no-dupe-args": "error",
  "no-dupe-class-members": "error",
  "no-dupe-else-if": "error",
  "no-dupe-keys": "error",
  "no-duplicate-case": "error",
  "no-empty-character-class": "error",
  "no-empty-pattern": "error",
  "no-ex-assign": "error",
  "no-fallthrough": "error",
  "no-func-assign": "error",
  "no-import-assign": "error",
  "no-inner-declarations": "error",
  "no-invalid-regexp": "error",
  "no-irregular-whitespace": "error",
  "no-loss-of-precision": "error",
  "no-misleading-character-class": "error",
  "no-new-native-nonconstructor": "error",
  "no-obj-calls": "error",
  "no-prototype-builtins": "error",
  "no-self-assign": "error",
  "no-self-compare": "error",
  "no-setter-return": "error",
  "no-sparse-arrays": "error",
  "no-this-before-super": "error",
  "no-unexpected-multiline": "error",
  "no-unreachable": "error",
  "no-unsafe-finally": "error",
  "no-unsafe-negation": "error",
  "no-unsafe-optional-chaining": "error",
  "no-unused-labels": "error",
  "no-unused-private-class-members": "error",
  "no-unused-vars": ["error", { vars: "local", args: "none", caughtErrors: "none" }],
  "no-useless-backreference": "error",
  "use-isnan": "error",
  "valid-typeof": "error",
};

module.exports = [
  { ignores: ["runtime/**", "build_macos/**", "dist/**", "installer/**", "web/data.js"] },
  { files: ["web/**/*.js"], languageOptions: { ecmaVersion: 2023, sourceType: "script" }, rules: bugs },
  { files: ["tests/**/*.cjs", "eslint.config.cjs"], languageOptions: { ecmaVersion: 2023, sourceType: "commonjs" }, rules: bugs },
];
